### PR TITLE
[ISSUE-1300] fix: TOPIC_REGEXP

### PR DESCRIPTION
**Pull request by CandyFet**
Resolves https://github.com/karafka/karafka/issues/1300

### CODE REVIEW

**Comment by nijikon** [comment]
If nothing changed, I think that valid characters for Kafka topics are the ASCII alphanumerics, `.`, `_`, and `-`, and it is better not to mix `.` and `_` to avoid metric namespace collisions.

**Comment by CandyFet** [comment]
So we should count as valid names strings that contain chars and `.` and `-`, or `-` and `_`?
`ус.auth.cmd.shopper-registrations.1` -> valid
`ус_auth_cmd_shopper-registrations_1` -> valid
`ус.auth.cmd.shopper-registrations_1` -> invalid

**Comment by nijikon** [comment]
@CandyFet that is a good choice. Plus, we should not allow adding both `test_1` and `test.1` Because that would end with `Topic 'test.1' collides with existing topics: test_1`

**Comment by mensfeld** [comment]
Hey @CandyFet. I agree with @nijikon I will rework this piece of validation next week to make sure we allow the broader (allowed) scope of topic names but that we don't run into collisions. Got just back from a longer travel, hence delay

**Comment by CandyFet** [comment]
@nijikon @mensfeld Hey guys, please take a look on a new changes

**Comment by mensfeld** [comment]
@CandyFet on a first glimpse looks good. Once I close one other functionality I'm working on (today or tomorrow), I will review, approve and schedule for the upcoming karafka release.

**Comment by mensfeld** [comment]
As long as specs are ok I will merge and handle styling. No need for you to deal with this. Great work!

**Comment by mensfeld** [comment]
@CandyFet  thank you for your contribution. I still need to fix one thing related to admin timeouts on topic creation but that is not related to your PR code. It's accepted and will be released in the upcoming release.

**Comment by mensfeld** [comment]
@CandyFet 2.0.31 has been released with your contribution. Thank you :pray:

**Pull request merged**
