### PR TITLE
Add backward compatibility for params metadata attributes

### PR DESCRIPTION
**Pull request by rabotyaga**
Related to: https://github.com/karafka/karafka/pull/604

### CODE REVIEW

**Comment by mensfeld** [comment]
I don't think we should. That's why it's a breaking changes release `1.4` instead of `1.3.x`. This is backported by me from 2.0 but I'm open for discussion.

**Comment by rabotyaga** [comment]
I have no strong opinion here, if this was exactly the plan then it's perfectly fine for me.
Just had thought at first, that this breaking change is too much breaking for incrementing only the minor number.

**Comment by mensfeld** [comment]
Actually after giving it a second look and thought I think we can merge this. You're arguement is strong and due to 2.0 I feel we can add it to 1.4 and remove in 2.0.

I really appreciate your help 😊

**Comment by mensfeld** [comment]
Would you mind reopening? I would love to merge it to rc2

**Comment by rabotyaga** [comment]
Thanks!

**Comment by mensfeld** [comment]
🙏

**Comment by rabotyaga** [comment]
Should I add specs or wrap with some kind of deprected warnings?

**Comment by mensfeld** [comment]
Specs are always welcomed :)

I don't think we need to add deprec. 2.0 bump should be enough with extensive upgrade notes that I always release.

One thing worth considering is using a direct struct keys reference for methods forwarding instead of referencing manually. That way if we would add some sort of metadata in 1.4.x we would not have to remember to update it anywhere else expect in the metadata struct and it's builder.

**Review by mensfeld — APPROVED** [review]

**Pull request merged**
