### PR TITLE
Create a Datadog::LoggerListener based on the Karafka::Instrumentation::LoggerListener

### PR DESCRIPTION
**Pull request by bruno-b-martins**
Hey guys 👋

I've adapted `Karafka::Instrumentation::LoggerListener` to trace consumers in Datadog.
Since Datadog charges per log event, I removed the "polling" messages and focused only on the messages' consumption and errors.

It's not much, but I think it would be nice to make it available for everyone.

### CODE REVIEW

**Comment by mensfeld** [comment]
O wow nice! Don't worry about the failing specs, I will take care of it as I did not yet fully figure out how to run specs out of forks. :pray:

**Comment by mensfeld** [comment]
I will take a look at it probably next week as I have a cold now and will be traveling in few days.

**Comment by bruno-b-martins** [comment]
> O wow nice! Don't worry about the failing specs, I will take care of it as I did not yet fully figure out how to run specs out of forks. 🙏

Well, I had a quick look into them and tried to improve it, but now the CI didn't ran 😅 

Perhaps you can have a look another day 🤞

**Comment by mensfeld** [comment]
> Well, I had a quick look into them and tried to improve it, but now the CI didn't ran sweat_smile

No idea why it did not run. I do have idea why it does not run on forks though. It's because I inject pro license and its an ENV variable. Will try to tackle it soon.

**Comment by mensfeld** [comment]
@bruno-b-martins getting back home tomorrow. Should tackle it before the weekend

**Comment by bruno-b-martins** [comment]
Cool. Don't stress it too much. And do let me know if I can help somehow (this week I'll be a bit offline though).
See ya 👋

**Comment by mensfeld** [comment]
@bruno-b-martins any chance on getting a printscreen for this on how that works in DD? I could include it in the docs :pray:

**Comment by bruno-b-martins** [comment]
Hey @mensfeld :wave:

Here you go:

A success trace:
Screenshot 2022-11-05 at 09 24 16

And an error trace:
Screenshot 2022-11-05 at 09 35 27

**Review by mensfeld — APPROVED** [review]

**Comment by mensfeld** [comment]
Going to merge it to a separate branch to apply potential improvements/specs and then target master. I haven't yet figured out how to run integrations of forks and want to add something there.

FYI I will also prepare docs how to run all the integration specs, etc in Karafka but as always :clock1:

**Comment by bruno-b-martins** [comment]
Sure! Great work man! See you around 👋

**Comment by mensfeld** [comment]
Not sure if pinging from other issues work so here's the PR I would love for you to review and check: https://github.com/karafka/karafka/pull/1122

once done I will merge to master and once I have docs updated, will craft a release.

**Pull request merged**
