### PR TITLE
Makes sure the log directory exists when is possible

### PR DESCRIPTION
**Pull request by robertomiranda**
`ensure_dir_exists` it's causing an issue when is performed over `log` and the directory is read-only.

### CODE REVIEW

**Comment by mensfeld** [comment]
Thank you! I'll look into that during the weekend!

**Comment by mensfeld** [comment]
Thank you and sorry for the delay!

**Comment by mensfeld** [comment]
Postmerge review - @robertomiranda why did you use `world_writable?` instead of `writable?`

**Comment by robertomiranda** [comment]
@mensfeldI just wanted keep the File method name 😅. Thanks much for merging this PR 🙇

**Pull request merged**
