### PR TITLE
bump-gems-2019-12-18

### LINKED ISSUE #559: Bump thor version to 1.0.0
From gitter cc @mensfeld 
> Hey guys,
I run a pipeline against rails master version in my project and recently ( yesterday) they enforced thor version 1.0 with this commit: [rails/rails@fe9abe4](https://github.com/rails/rails/commit/fe9abe44360d12940fa385a3992350f07a361e3d) which makes my RAILS_MASTER=1 bundle update rails fail.
However karafka supports thor ~0.20. Do you think it's possible to bump/upgrade thor version?

### PR DESCRIPTION
**Pull request by chaadow**
@mensfeld Tried to follow the same commit message format you guys do for gem bumping 👌 
closes #559

### CODE REVIEW

**Comment by mensfeld** [comment]
LGTM! Thank you <3

**Comment by mensfeld** [comment]
Waiting for the CI to report and will a) merge b) craft a release.

**Comment by nijikon** [comment]
Thanks @chaadow

**Comment by peterhoeg** [comment]
Is there a plan for a new release with this change?

**Comment by mensfeld** [comment]
Hmmm @peterhoeg didn't I do it? 0_o let me check

**Comment by mensfeld** [comment]
@peterhoeg lgtm: https://rubygems.org/gems/karafka/versions/1.3.4

**Comment by peterhoeg** [comment]
Sorry, yes, you are right. `bundler` picked an earlier version due to another gem version constraint. My apologies. But GH doesn't have the release or am I missing something?

**Comment by mensfeld** [comment]
@peterhoeg yeah maybe. TBH I don't consider GH as the releases source. @nijikon tags things for me usually but it seems it somehow got lost. Really sorry for that.

**Pull request merged**
