### PR TITLE
reorder config comments to match options with docs

### PR DESCRIPTION
**Pull request by filiptepper**

### CODE REVIEW

**Comment by nijikon** [comment]
@mensfeld I think that we should have it ordered alphabetically in both here and the docs. What do you think?

**Comment by mensfeld** [comment]
@nijikon I don't mind renaming the karafka section for configs to be alphabetical but this "random" order within Kafka section is not random at all. It matches Ruby-kafka settings declarations in various places and helps me track changes and stay in sync with proper argument and options injection through ruby-kafka client lifetime.

See for example:

https://github.com/karafka/karafka/blob/master/lib/karafka/setup/config.rb#L80
and https://github.com/zendesk/ruby-kafka/blob/master/lib/kafka/client.rb#L284

The order is the same.

**Comment by nijikon** [comment]
I understand your argument here, but now we have `pause_timeout` which is not in that file. So how is that to the whole concept?

**Comment by mensfeld** [comment]
@nijikon yes. The `pause_timeout` should be removed from this section and moved out. Feel free to check the orders of particular `kafka.` namespace options and match them with corresponding Karafka options to get them in proper (matching) order in a separate PR :). Thanks in advance!

**Pull request merged**
