### PR TITLE
haml-lint changed name to haml_lint

### PR DESCRIPTION
**Pull request by potomak**
Fixes on `bundle install`:

    An error occurred while installing haml-lint (0.13.0), and Bundler cannot continue.
    Make sure that `gem install haml-lint -v '0.13.0'` succeeds before bundling.

See also: https://github.com/polishgeeks/polishgeeks-dev-tools/issues/58.

### CODE REVIEW

**Comment by mensfeld** [comment]
@potomak  great work! could you just remove the .rubocop file? It is unnecessary since we ship with polishgeeks-dev-tools .rubocop file

**Comment by potomak** [comment]
Well, I can't without breaking the build because of:

```
RSpec/AnyInstance:
  Enabled: false
RSpec/MultipleDescribes:
  Enabled: false
RSpec/InstanceVariable:
  Enabled: false
RSpec/FilePath:
  Enabled: false
```

Is there another way to partially override polishgeeks-dev-tools' rubocop configuration?

**Comment by mensfeld** [comment]
@potomak that is true - we can use custom rubocop for now, since in few months we will drop devtools gem in favour of something new that is more independent. I will review this today

**Comment by mensfeld** [comment]
Added to #78 branch

**Pull request closed without merging**
