### PR TITLE
Wrap worker/job execution with rails reloader or executor

### PR DESCRIPTION
**Pull request by mensfeld**
continuation of https://github.com/karafka/karafka/pull/2232

### CODE REVIEW

**Comment by mensfeld** [comment]
@fusion2004 technically user code should be called only in the `job.call`, thus I simplified it.

Checking the boolean is 10-15x faster than running a proc dummy chain.

**Comment by mensfeld** [comment]
I also renamed it to reflect what it does. It does not wrap ALL worker work thus the name seemed not to be perfect. I align it and other pieces of job flow are not part of user code, thus this should be enough. Works on my machine well. Lets see the test suite and waiting on your checks.

**Review by fusion2004 — APPROVED** [review]
Yep, working great for me as well!

I wasn't a huge fan of the proc dummy chain either, but I was borrowing that approach from sidekiq. 👍

**Comment by mensfeld** [comment]
Merged. I should wrap this release in a few days.

**Pull request merged**
