### PR TITLE
Add `use_distributions` setting to Datadog::MetricsListener

### PR DESCRIPTION
**Pull request by Aerdayne**
Currently, histogram metrics are emitted as histograms in the Datadog listener.
This PR introduces an option to emit these metrics as distributions instead. This makes the calculated percentiles more accurate in case there are multiple consumers running on different hosts (or rather when multiple DD agents are being used).
More info can be found in the [DD documentation](https://docs.datadoghq.com/metrics/types/?tab=distribution#metric-types).

### CODE REVIEW

**Comment by mensfeld** [comment]
:wave: I'll pick it up in the upcoming days :pray:

**Comment by mensfeld** [comment]
@Aerdayne this looks good. I only have a conceptual remark and I am happy to apply it if you do not want or do not have time:

I do not like `use_distribution` config. I would rather have `distribution_mode` and have it set o `:histogram`. Then we could use the `#distribution` method like other metric types and underneath use context awareness to pass to the client. This would in my opinion be a bit more readable because it would not introduce the public send

**Review by mensfeld — COMMENTED** [review]
comment in the comments ;)

**Comment by Aerdayne** [comment]
So you mean something like this?

```ruby
case distribution_mode
in :histogram
  histogram(...)
  # ...
in :distribution
  distribution(...)
  # ...
end
```

**Comment by mensfeld** [comment]
> So you mean something like this?
> 
> ```ruby
> case distribution_mode
> in :histogram
>   histogram(...)
>   # ...
> in :distribution
>   distribution(...)
>   # ...
> end
> ```

exactly :)

**Comment by mensfeld** [comment]
Thank you for the PR btw. I know karafka DX from the contributor perspective is shit at the moment :(

**Review by mensfeld — APPROVED** [review]

**Comment by mensfeld** [comment]
@Aerdayne  I applied a small refactor on top of your code. Would you mind taking a look? https://github.com/karafka/karafka/pull/1928 I cannot assign you as the reviewer so pinging you here

**Pull request merged**
