### PR TITLE
Make waterdrop send_messages and raise_on_failure configurable

### PR DESCRIPTION
**Pull request by ankitagupta12**
### Issue
- https://github.com/karafka/karafka/issues/225

### Fix
- Define new settings inside `Karafka::Setup::Config`
- Use the settings from `config` object inside `Karafka::Setup::Configurators`

### CODE REVIEW

**Comment by mensfeld** [comment]
@ankitagupta12 could you please namespace those settings into the ```producer``` namespace, similar to how kafka is made? Having a ```raise_on_failure``` message in a general scope is not enough descriptive as there are many failures in kafka world :)

**Comment by ankitagupta12** [comment]
Hi @mensfeld. Thanks for the suggestion. I've added the settings to a namespace

**Comment by mensfeld** [comment]
@ankitagupta12 will review that during the weekend. Thank you for the updates

**Comment by mensfeld** [comment]
Won't merge as 1.1 copies all the common settings and the rest can be postreconfigured with waterdrop 1.0.

**Pull request closed without merging**
