### PR TITLE
Update CI links in README.md

### PR DESCRIPTION
**Pull request by simi**
- replace Travis CI links with GitHub Actions ones

### CODE REVIEW

**Review by mensfeld — APPROVED** [review]

**Comment by mensfeld** [comment]
muchas gracias - I still have no idea why statuses are not bein reported but I will check it upcoming week.

**Comment by simi** [comment]
Aren't you missing pull_request at https://github.com/karafka/karafka/blob/master/.github/workflows/ci.yml#L4?

See RG actions for example https://github.com/rubygems/rubygems/blob/8a6c3b6d16bc896c9ceacf6f87588f4edf95647d/.github/workflows/ubuntu-rubygems.yml#L3-L9.

It reports on each pull request and also for particular branches on push.

**Comment by mensfeld** [comment]
aaaaaa great point! I will fix that in a second in the whole ecosystem. THANK YOU!

**Comment by mensfeld** [comment]
Works! Amazing! Will propagate this to all the repos and get back to this one. Thank you once again.

**Comment by mensfeld** [comment]
@simi all fixed. You've motivated me so I fixed CI on all repos + fixed the docs references on all as well :) have a great weekend.

**Comment by simi** [comment]
Great to hear @mensfeld!

**Pull request merged**
