### PR TITLE
Added a zookeeper 'namespace' option.

### PR DESCRIPTION
**Pull request by jwkoelewijn**
Zookeeper instances can be namespaces, meaning that all znodes are
prefixed with the same name. This means that broker information would be
found at /namespace/brokers/ids instead of /brokers/ids.

This feature branch adds support for this, defaulting to an empty
namespace. Specs have been added to test the functionality.

### CODE REVIEW

**Comment by mensfeld** [comment]
Hey - we wont merge this as were working on providing that as a part of a bigger fuctionality, however pleaase look here: #59 there is a temporarily solution for that. I will keep your code open as we will use it as a base for this part of the biger change. Thank you!

**Comment by jwkoelewijn** [comment]
Ow, did not see that, just started hacking away :)

Did not know other people were having the same setup as we do, good luck and feel free to use or delete any of my code :)

**Comment by mensfeld** [comment]
@jwkoelewijn  there are more people like that :) I will keep that open since we will use this code soon. Thank you for your contribution and if you have any questions/problems feel free to ask!

**Comment by mensfeld** [comment]
Once the #88  is merged, I will take care of that

**Comment by mensfeld** [comment]
Incorporated into #89 - thank you @jwkoelewijn!

**Pull request closed without merging**
