### PR TITLE
Support override of max_bytes_per_partition

### PR DESCRIPTION
**Pull request by lardcanoe**
Add this config setting so that Karafka will work when Kafka's server settings `fetch.message.max.bytes` and `max.request.size` have been overridden.

### CODE REVIEW

**Comment by mensfeld** [comment]
Hey @lardcanoe - thank you for your contribution. We will review it shortly.

**Comment by lardcanoe** [comment]
Failures are due to:

> lib/karafka/connection/topic_consumer.rb:57:7: C: Metrics/MethodLength: Method has too many lines. [16/15]

I'm not sure I feel comfortable refactoring that function. Thoughts?

**Comment by mensfeld** [comment]
@lardcanoe  please leave it as it is. I was thinking of making it a bit different to make it work easier with Ruby-Kafka. I will refactor that :)

**Comment by mensfeld** [comment]
@lardcanoe quick update: I'm still on it. It's just a bigger refactoring and you guys (which is awesome!) keep giving me more and more pull requests :dancer:

**Comment by mensfeld** [comment]
Ok, I now have a concept on how I want to do this :) - starting now :dancing_men:

**Comment by mensfeld** [comment]
I will merge it so people can use it. Rewritten in 0.6 :) Thank you!

**Pull request merged**
