### PR TITLE
Draft: add prometheus listener

### PR DESCRIPTION
**Pull request by vadim-handy**
**STATUS: WIP**

Adding a prometheus exporter listener to karafka

Prometheus Exporter - https://github.com/discourse/prometheus_exporter

Since the Collector is not in prometheus exporter the server would need to be started like so: 

```
BUNDLE_PATH="/usr/local/bin/bundle"
COLLECTOR_PATH="lib/karafka/instrumentation/vendors/prometheus_exporter/metrics_collector.rb"
KARAFKA_PATH=$($BUNDLE_PATH info --path karafka)/$(COLLECTOR_PATH) 
$BUNDLE_PATH exec prometheus_exporter --bind 0.0.0.0 --verbose --histogram --type-collector $KOURIER_PATH
```

In K8s the prometheus exporter will need to live within the karafka server pod as a sidecar like so: 

```yaml
kind: Deployment
apiVersion: apps/v1
metadata:
  name: myapp-karafka
spec:
  revisionHistoryLimit: 5
  replicas: 1
  selector:
    matchLabels:
      service: myapp
      app: karafka
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        service: myapp
        app: karafka
    spec:
      volumes: []
      containers:
      - name: prometheus-exporter
        command:
        - "/bin/bash"
        - "-c"
        - |
          BUNDLE_PATH="/usr/local/bin/bundle"
          KOURIER_PATH=$($BUNDLE_PATH info --path kourier)/lib/karafka/instrumentation/vendors/prometheus_exporter/metrics_collector.rb
          $BUNDLE_PATH exec prometheus_exporter --bind 0.0.0.0 --verbose --histogram --type-collector $KOURIER_PATH
        image: my-ecr:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 9394
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 512Mi
          requests:
            cpu: 20m
            memory: 384Mi
      - name: karafka
        image: my-ecr:latest
        resources:
          requests:
            cpu: "1"
            memory: 1Gi
          limits:
            cpu: "1"
            memory: 2Gi
        lifecycle:
          preStop:
            exec:
              command:
              - "/bin/bash"
              - "-c"
              - "pkill -TSTP -f karafka; sleep 60;"
        command:
        - "/bin/bash"
        - "-c"
        - |
          until curl -s http://localhost:9394/ping > /dev/null; do echo waiting for prometheus-server; sleep 1; done;
          RAILS_ENV=production /usr/local/bin/bundle exec karafka server --exclude-consumer-groups karafka_web
        ports:
        - containerPort: 3000
          protocol: TCP
        livenessProbe:
          failureThreshold: 12 # 12 * 10s = 2 minutes of extra processing time after a missed poll interval
          initialDelaySeconds: 30
          httpGet:
            path: /
            port: 3000
            scheme: HTTP
        env: []
        imagePullPolicy: Always
        volumeMounts: []
      terminationGracePeriodSeconds: 300
```

Still needed:

- [ ] Refactoring the messy bits
- [ ] Testing metric conversions
- [ ] Testing that all metrics are reported accurately 
- [ ] Example rails app w/ prometheus exporter in examples repo
- [ ] Add params, return types, fix wrong types
- [ ] Better error handling

### CODE REVIEW

**Comment by vadim-handy** [comment]
@mensfeld - This is still in progress but has enough detail for an initial review whenever you have time. 

There are a few things I'm still figuring out a best path forward for: 
- Configuring metrics
  - Right now this is stored in a yaml file so it can be shared between the karafka + prometheus_exporter server without needing to load an entire application's dependencies into the prometheus server. Otherwise to get `MetricsListener.config.rd_kafka_metrics` the exporter server would need to load karafka + rails (if in a rails app).
- Who owns the collector 
  - Usually the collector lives in the prometheus_exporter repo. For now I've put it within karafka until this is further along. Additionally, prometheus_exporter would need to support collector configurations in some way (histogram buckets per metric for collectors, what metrics to observe, etc) - there's currently no collector that does - we can figure this out later. If/When this is included in the exporter repo there'd be 3 repos to keep in sync (karafka, waterdrop, exporter).
- Filling in the gap for `on_statistics_emitted` spec coverage + testing that they're configurable
- Metric conversion. Ideally we adhere to prometheus metric standards https://prometheus.io/docs/practices/naming/. For rd_kafka, I'm using the converter in the yaml config. For karafka, at the moment I'm just dividing where expected - I still need to move this to use the config.
- General refactoring - some of the things could be simplified or improved.

**Comment by mensfeld** [comment]
@vadim-handy I will review this PR this week :pray:

**Comment by mensfeld** [comment]
@vadim-handy just so you know, I never forgot it. It is on my roadmap

**Comment by mensfeld** [comment]
Going to close it. Feel free to reopen anytime you want to work on this :)

**Pull request closed without merging**
