### PR TITLE
Fix typo in comment

### PR DESCRIPTION
**Pull request by quynhethereal**
Just some minor typos I found while reading the code

### CODE REVIEW

**Comment by quynhethereal** [comment]
@mensfeld Please help me trigger the CI again as I added one more typo into the PR. (It is quite weird that the spec would fail tho 🤔 )

**Comment by mensfeld** [comment]
@quynhethereal it will trigger after the previous fails fully. It's one spec that fails sometimes that I am trying to fix. I improved several specs stability down the road but once in a while something will pop up. Don't worry about it

**Comment by mensfeld** [comment]
Ah forks don't have access to ENV keys. Nvmd that for this PR :)

**Comment by mensfeld** [comment]
Yeah just ignore it, ping me when you are done. Hope you enjoy the code-base and find the docs descriptive.

If there is anything I can improve, don't hesitate to point it out.

**Comment by quynhethereal** [comment]
Ah I was talking about the CI as all the integration tests have failed (perhaps due to ENVs key (?) that you describe?). Does that mean that this PR can't be merged?

**Comment by mensfeld** [comment]
PR will be merged ;) don't worry.

I was talking about you reading the docs ;)

**Comment by quynhethereal** [comment]
Oh haha. True, I will probably find more typos as I go so it is best to just leave it for open for now so I can add more commits to it. 

Side note, I made some fixes in the Wiki as well ;) It is very descriptive and informative btw.

**Comment by mensfeld** [comment]
> Oh haha. True, I will probably find more typos as I go so it is best to just leave it for open for now so I can add more commits to it.

Sure. I will keep it open until you declare it's done and then I can run all specs and integrations with the key.

> Side note, I made some fixes in the Wiki as well ;) It is very descriptive and informative btw.

Thank you. I will sync that and deploy to https://karafka.io/docs as well after the weekend.

:pray:

**Comment by quynhethereal** [comment]
Hi @mensfeld, feel free to merge the PR now. I think I have done reading 👍

**Comment by mensfeld** [comment]
Thank you! I hope you had a good time :)

**Pull request merged**
