### PR TITLE
Jwkoelewijn zookeeper namespace support

### PR DESCRIPTION
**Pull request by mensfeld**
@agwozdowski @pavlo-vavruk  please review. This is based on work of @jwkoelewijn from #86 - thank you very much!

### CODE REVIEW

**Comment by agwozdowski** [comment]
👍

**Comment by jwkoelewijn** [comment]
No problem at all :)

**Comment by jwkoelewijn** [comment]
Very awesome this functionality was added, and now I finally had the time to actually try it on our staging environments. Turns out we forgot to change the way Poseidon::ConsumerGroup registers itself within Zookeeper.

The current solution does indeed find the Kafka Brokers within a chrooted Zookeeper, but when the consumer-groups are being registered, this chrooted environment is completely ignored, resulting in a quite confusing Zookeeper topology :)

I will try and see if I can supply a fix, but I see that poseidon_cluster is deprecated in favour of karafka, but karafka is still depending on it.... I might just create a fork of poseidon_cluster and make a pull-request here pointing to that or something like that... what do you reckon?

Btw, if I should've posted this under issues, please tell me and I will move it there.

JW

**Comment by mensfeld** [comment]
@jwkoelewijn  Karafka is dependent on it until the kafka-ruby consumer is produciton ready. Unfortunately they still have more issues than Poseidon, that's why we stay with it. Meanwhile you can try to patch poseidon cluster here (as a part of Karafka).

**Pull request merged**
