### PR TITLE
[#535] Add Params benchmark

### PR DESCRIPTION
**Pull request by rabotyaga**
Related to: #535

### CODE REVIEW

**Comment by nijikon** [comment]
@rabotyaga can you push an empty commit message to retrigger actions?

**Comment by nijikon** [comment]
OK, need to debug this, will have a look later today.

**Comment by rabotyaga** [comment]
@nijikon Probably you have to turn on `Run workflows from fork pull requests`, if it's not on already
https://github.com/karafka/karafka/settings/actions

**Comment by mensfeld** [comment]
It's on 0_o. @nijikon will check it but meanwhile I will craft a release.

**Comment by mensfeld** [comment]
I'm merging this to master (1.3) without the fix atm.

**Comment by nijikon** [comment]
Sounds good. I will try to reproduce and fix the issue this week.

**Pull request merged**
